meta_product_name: "Beerware"
meta_title: "Beerware - your next craft beer "
meta_description: "App where you can find Lisbon craft beers, mark them as drank or to be drank, check beer lovers’ opinions and all the breweries around the city."
meta_image: "cover.png" # should exist in `app/assets/images/`
